sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 133483
  redis:
    host: localhost
    port: 6379
    password: 133483
    database: 0
  wechat:
    appid: wx47a7a7c7fda1ceda
    secret: f0b87b8404dd1daf32661c1509814079

